version: '3.1'
services:
    backend:
        environment:
            ATLAS_URI: 'mongodb://ytdl-mongo-db:27017'
            PORT: 3031
            SESSION_SECRET: 
            VERIFICATION_EMAIL: 
            VERIFICATION_PASSWORD: 
        build: .
        volumes:
            - ".:/app"
        ports:
            - "3031:3031"
        depends_on:
            - db
    db:
        image: mongo:4.4.11
        container_name: yipc-mongo-db
        restart: always
        ports:
            - "28017:28017"
        volumes:
            - /nfs/Data/year-in-pixels-creator/db/:/data/db