version: '3.1'
services:
    backend:
        environment:
            ATLAS_URI: 'mongodb://ytdl-mongo-db:27017'
            PORT: 3031
            SESSION_SECRET: 
            VERIFICATION_EMAIL: 
            VERIFICATION_PASSWORD: 
        build: .
        volumes:
            - ".:/app"
        ports:
            - "3031:3000"
        depends_on:
            - db
    frontend:
        build: .
        volumes:
            - "./app:/app"
        ports:
            - "3003:3000"
        depends_on:
            - backend
    db:
        image: mongo        
        container_name: yipc-mongo-db
        restart: always
        ports:
            - "28017:28017"
        volumes:
            - /nfs/Data/yipc/db/:/data/db